version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    depends_on:
      - db
  db:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: pandey31
      MYSQL_USER: 'nageshwar'
      MYSQL_PASSWORD: 'DtnPkAlpxWTC9CkE:'
    ports:
      - "3306:3306"
pma:
    image: phpmyadmin/phpmyadmin:latest
    container_name: pma
    environment:
      PMA_HOST: 127.0.0.1
    network_mode: host
    volumes:
      - ./def.conf:/etc/apache2/sites-available/000-default.conf
      - ./ports.conf:/etc/apache2/ports.conf
